### ISSUE TITLE
关于ChopperBot如何添加投稿账号的问题

### ISSUE THREAD

**Issue by itgoyo** [Geniusay/ChopperBot#50]
<img width="1917" alt="image" src="https://github.com/Geniusay/ChopperBot/assets/23348551/a1d2169e-5dc7-4a8c-ba18-6a3ebaefef95">

项目基本跑起来了，看到也可以添加主播，和类似订阅热门的主播，我这边有个问题就是，看到项目简介里面是有自动投稿的功能的，但是我没找到对应的账号登录的地方，请问对应的位置在哪里呢，或者说应该如何正确添加。类似biliup那种添加类似cookies.json文件。期待您的回复。

**Comment by lishang520** [comment]
> <img alt="image" width="1917" src="https://private-user-images.githubusercontent.com/23348551/301123082-a1d2169e-5dc7-4a8c-ba18-6a3ebaefef95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzUwODEsIm5iZiI6MTcwNjc3NDc4MSwicGF0aCI6Ii8yMzM0ODU1MS8zMDExMjMwODItYTFkMjE2OWUtNWRjNy00YThjLWJhMTgtNmEzZWJhZWZlZjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MzFmYmEwNDM0ZTBmZjE0ZjljMzBlOTNjNDRlMmI0NTVmMDk2MzZiNzQxYTk0OWI0YWIxNWU0ZDIyMDdhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYltGV_TFDENiU3njHNLUUmIyIPqP-PRNCcEsmNrzss">
> 项目基本跑起来了，看到也可以添加主播，和类似订阅热门的主播，我这边有个问题就是，看到项目简介里面是有自动投稿的功能的，但是我没找到对应的账号登录的地方，请问对应的位置在哪里呢，或者说应该如何正确添加。类似biliup那种添加类似cookies.json文件。期待您的回复。

你好，请问怎么部署呀？您是直接使用的这个源码部署的嘛？有教程嘛？

**Comment by lishang520** [comment]
> <img alt="image" width="1917" src="https://private-user-images.githubusercontent.com/23348551/301123082-a1d2169e-5dc7-4a8c-ba18-6a3ebaefef95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzM5MjAsIm5iZiI6MTcwNjgzMzYyMCwicGF0aCI6Ii8yMzM0ODU1MS8zMDExMjMwODItYTFkMjE2OWUtNWRjNy00YThjLWJhMTgtNmEzZWJhZWZlZjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAwMjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMWNiOTY0ZDZhYWNlOTA5NTg5NzkyOGU4MWVhNmJmNTk2YzZhNGEzZmFlMzcwMjNhOTY5ZmRiNzIwMzMzNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rLXnk_tgclXdzZJfZHHgYApN_oRw4QAyUUFexxcI_dQ">
> 项目基本跑起来了，看到也可以添加主播，和类似订阅热门的主播，我这边有个问题就是，看到项目简介里面是有自动投稿的功能的，但是我没找到对应的账号登录的地方，请问对应的位置在哪里呢，或者说应该如何正确添加。类似biliup那种添加类似cookies.json文件。期待您的回复。

我也是走到这一步了，点击添加账号，但是没反应。而且我的照片、集合、主题数据那几个栏目都是空白的，已经配置了key呀

**Comment by Geniusay** [comment]
前端目前还在编写中 今晚会更新部分前端内容 因为我主职是后端 所以前端更新较慢 不好意思😥

**Comment by itgoyo** [comment]
> 前端目前还在编写中 今晚会更新部分前端内容 因为我主职是后端 所以前端更新较慢 不好意思😥

客气嘞您，持续保持关注，加油大大！ 😄

**Comment by Geniusay** [comment]
@itgoyo 目前项目是只做了windows适配 但是后续推出的版本 会适配其他系统，切片的话是在/config/liveRecord/online下面对应的直播平台中可以看到对应的切片，如果有报错的话 可以发一下报错截图 我看一下是什么 问题

**Comment by itgoyo** [comment]
> @itgoyo 目前项目是只做了 windows 适配 但是后续推出的版本 会适配其他系统，切片的话是在 /config/liveRecord/online 下面对应的直播平台中可以看到对应的切片，如果有报错的话 可以发一下报错截图 我看一下是什么 问题

感谢大大，我这边把java jdk切换到11 win上也运行正常了，暂时没有问题了

**Comment by aoecal** [comment]
我也是在搭建部署上遇到了问题,不知道能否给与指导,
