### ISSUE TITLE
源代码部署缺失类 org.example.core.guard.VideoPushGuard

### ISSUE THREAD

**Issue by heihei180** [Geniusay/ChopperBot#62]
hi community：

我发现运行代码会报找不到类的错误：
`org.example.core.guard.VideoPushGuard`
想问下这是类丢失了吗？还是属于生成的类呢？

使用vscode 从master分支的搜索结果：
只有使用的代码，没有定义的代码

![image](https://github.com/Geniusay/ChopperBot/assets/38102241/3ebb3fed-6f1a-4ba6-b728-15fe8c8573a2)

**Comment by Geniusay** [comment]
这个在昨天的pr刚删掉该代码

**Comment by Geniusay** [comment]
@welsir 来解答一下

**Comment by welsir** [comment]
你好 这个报错是因为在昨天的pr中替换了该类的命名 你需要更新一下fork仓库至最新版本即可使用 @heihei180

**Comment by welsir** [comment]
@heihei180 你只需要把这个import给删掉即可 不会有其他代码层面的引用

**Comment by welsir** [comment]
这是我的问题 在昨晚pr的时候没有检查类的替换 我等会交一版新的代码

**Comment by Geniusay** [comment]
@welsir 你去把你的错误引用给删除 然后交一个pr 解决这个issue

**Comment by welsir** [comment]
是的 你也可以手动更改
